server:
  port: 7779
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3309/tool_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: root
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3309/tool_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
    default:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3309/tool_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root

  redis:
    host: localhost
    port: 6379
#    database: 2
#    password:
#logging:
#  pattern:
#    console: "$d - $msg%n"
#  path:
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.up.platform.entity
#  not-empty: true
#  identity: MYSQL
#  configuration:
#    mapUnderscoreToCamelCase: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
